### PR TITLE
Max-width slider

### PR DESCRIPTION
**Pull request by thirstyice**
see #137

### CODE REVIEW

**Comment by kid47** [comment]
The slider in the pushed version is re-sizing itself just in case anyone didn't notice

**Comment by thirstyice** [comment]
What do you mean?

**Comment by kid47** [comment]
It spanned the width of the page and resized itself

**Comment by thirstyice** [comment]
Probably just the css loading

**Comment by kid47** [comment]
Well then it loaded for about 10 minutes

**Pull request merged**
