### PR TITLE
Changed colour of "a" tag

### PR DESCRIPTION
**Pull request by kid47**
Black and 50% grey, just like they ask in the visual identity standards. Other than that I didn't really have a reason better than I don't like the blue/purple that's the default

### CODE REVIEW

**Comment by thirstyice** [comment]
Give me a good reason to merge this and I will.

**Comment by kid47** [comment]
The links would comply with the visual identity standards as well  Also provides better contrast for if the website is in colorblind mode, and I find it looks more professional as we've customized even the links

**Comment by thirstyice** [comment]
The links are the same colour as normal text, which makes them difficult to tell apart, and if customization equals professionalism, then every 15-year-old with a tumblr should be making six figures. As for colour-blindness, it makes no difference whether the text is black or blue. In fact, with a deficiency in blue cones the text would appear nearly black.

**Comment by kid47** [comment]
Like I said originally, it's really just personal preference on my part. I prefer to have customized links in my projects, and I never said professionalism meant money. Do what you wish with it, that's why I made it a pull request. It's also a suggestion as to how we can make it look nicer, cause it's one thing that hasn't been considered yet

**Comment by thirstyice** [comment]
Closing: lack of significant purpose

**Pull request closed without merging**
