### PR TITLE
Grad quotes submissions changes

### PR DESCRIPTION
**Pull request by ArcticAvenger**
Added grad quotes submission page under main.
Added link to quotes submission page under the upcoming bulletins in index.htm

### CODE REVIEW

**Comment by kid47** [comment]
File should be placed within "/upcoming". Link pointer will also have to be changed in accordance

**Comment by ArcticAvenger** [comment]
Will do

**Comment by kid47** [comment]
Please don't create a new pull request each time something changes. It automatically updates everytime you change something without you having to resubmit it

**Comment by ArcticAvenger** [comment]
Is that better?

**Comment by kid47** [comment]
The link to the file now needs to be changed as well

**Comment by ArcticAvenger** [comment]
Sorry that took so long. I'm forgetful sometimes.

**Pull request merged**
