### PR TITLE
Google search box

### PR DESCRIPTION
**Pull request by kid47**
In relation to #83. The proposed custom google search box. Not perfect, but should help with usability and should hopefully get rid of some of the complaints. If people could look this over to see if it would actually be useful, that would be great

### CODE REVIEW

**Comment by thirstyice** [comment]
I move we replace the abe banner with a search box

**Comment by kid47** [comment]
Personally, I prefer it under the news. Looks a little rough to me, but I bet you we could make it look better with some formatting. What do you think?

**Comment by kid47** [comment]
Just for the record and future reference: Google does not link to files (e.g. PDFs) that have their own pages where they're imported into iframes, and so it won't deviate from our current set-up

**Comment by thirstyice** [comment]
I think I'm not quite satisfied with either location. Maybe at the top of content?

**Comment by kid47** [comment]
Like above the slider? Or spanning all three divs?

**Comment by thirstyice** [comment]
Above the slider. Unless spanning the three divs looks better.

**Comment by thirstyice** [comment]
Yeah, that looks better.

When this gets implemented I think we should just do it in one new commit, rather than merging the four commits in this branch.

**Pull request closed without merging**
