### PR TITLE
adding cbe buttons to rightside menu

### PR DESCRIPTION
**Pull request by owmygreenmatter**

### CODE REVIEW

**Comment by owmygreenmatter** [comment]
many apologies for amateurish presentation--UI is doing my head in. is it possible to only include the relevant commit and not the school council updates? it isn't letting me cherry pick, as far as i see.

**Comment by thirstyice** [comment]
Split a new branch off the previous commit, then cherry-pick into that and make a new pull request
`git checkout HEAD~3`
`git checkout -b random-branch-name`
`git cherry-pick <commit hash>`

**Comment by kid47** [comment]
I don't believe they're doing this in gitbash, so those commands are probably redundant

**Comment by thirstyice** [comment]
Well then no wonder they can't cherry pick

**Comment by owmygreenmatter** [comment]
i'd love to change the colour scheme. also i'm trying my hardest to avoid command lines, but if i must use them then i will. is this pull request ultimately of any use to you guys?

**Comment by kid47** [comment]
Mostly for proofreading code and a medium to let you know what needs to be fixed. A check point if you will. Other than that, not really

**Comment by kid47** [comment]
Just gotta ask: downtown has been super picky about the colours we've used in the past, so is this our go-ahead to start using more colours? Cause neither of those buttons are per-regulations

**Pull request closed without merging**
