### PR TITLE
Update index.htm

### PR DESCRIPTION
**Pull request by ArcticAvenger**
Add Grad Quote Submission link to the Upcoming bulletins

### CODE REVIEW

**Comment by thirstyice** [comment]
The added link doesn't point to anything

**Comment by ArcticAvenger** [comment]
I will fix that. Sorry about that.

**Comment by ArcticAvenger** [comment]
Do you think you could help me out or point me in the right direction? My knowledge of html is limited to google so I'm not entirely sure what exactly I'm doing, which also means I can't figure out what I did wrong.

**Comment by thirstyice** [comment]
It looks like you already have the linked page in a different branch. If you merge the two branches on your end, then everything should work out

**Pull request closed without merging**
