### PR TITLE
merging owmygreenmatter/master with thirstyice/learning-commons-integration

### PR DESCRIPTION
**Pull request by owmygreenmatter**
this will bring the latter branch up to speed as well as add all the learning commons-related changes from the former branch

### CODE REVIEW

**Comment by thirstyice** [comment]
Why was this done?

**Comment by owmygreenmatter** [comment]
to bring thirstyice:learning-commons-integration up to speed as well as add all the learning commons-related changes from owmygreenmatter:master

**Comment by thirstyice** [comment]
thirstyice:learning-commons-integration is a separate branch; it doesn't need to be "brought up to speed." This commit merged changes that are irrelevant, will cause merge conflicts, and won't solve any problems into a branch that didn't need them, without any verification or discussion taking place first.

**Comment by thirstyice** [comment]
I'm fixing this

**Comment by thirstyice** [comment]
Changes to be pushed are now in `learning-commons-final`

**Pull request merged**
