### PR TITLE
Parent council to main

### PR DESCRIPTION
**Pull request by kid47**
Move of parent council from the 'about us' tab to 'main' to improve visibility for parents

### CODE REVIEW

**Comment by thirstyice** [comment]
Closing if no response is given before february

**Comment by kid47** [comment]
Give me until Monday and I'll ask in person to see if it can happen. Otherwise, yea, go for it cause nothing's happened

**Comment by thirstyice** [comment]
Sure

**Comment by kid47** [comment]
Thank you! I'm slightly proud at the moment

**Comment by thirstyice** [comment]
This is happening, but not through this branch

**Pull request closed without merging**
