### PR TITLE
learning commons integration-draft

### PR DESCRIPTION
**Pull request by owmygreenmatter**
after much ado, learning commons section is fully integrated here. all pages should match the conventions set up by the rest of the website.

### CODE REVIEW

**Comment by owmygreenmatter** [comment]
oh, and just for clarification: only the "unfinished learning commons draft", "finished draft of learning commons integration", and "changed topmenu, fixed learning commons main" commits are the ones that matter here. the other three ultimately won't make any difference to the main master branch

**Comment by thirstyice** [comment]
Could you maybe include only those commits then?

**Comment by thirstyice** [comment]
Also, changes meant to be publicized **should not** include half-finished pages

**Comment by thirstyice** [comment]
Also, pdfs should be imported in the wrapper

**Comment by thirstyice** [comment]
Conclusion: not yet

**Comment by owmygreenmatter** [comment]
i'll get on the other stuff immediately, but where are you seeing half-finished pages? the only thing i can think of is the new arrivals/dvds page, which i suppose i could ask mr. roberts about--granted, that area of aberhart itself is only half-finished at the moment...

**Comment by owmygreenmatter** [comment]
also, whether or not to put each library pathways pdf in its own wrapper was a question we did wrestle with during the making of this pull request. with the sheer number of pdfs there, i'm of the opinion that a separate page for each pdf would quickly become incredibly cumbersome; plus, with the document index we do have a prerequisite for not putting those pdfs in wrappers. still, if you don't think that's right then i can make that change pretty quickly.

**Comment by kid47** [comment]
Should not be closed if still in progress

**Comment by kid47** [comment]
All commits seem to be important.
PDFs will soon be imported into wrappers.
Please elaborate on half finished pages.

**Comment by thirstyice** [comment]
Closed because it contains commits that are irrelevant to the pull request

**Comment by kid47** [comment]
All commits are actually essential to pull request however, unless you want him do it in one new one. Because it's taken so long, the only one that's questionable is the merge of master to update the branch. Otherwise, it's all necessary

**Comment by owmygreenmatter** [comment]
it's true that DVDs is technically an unfinished page, but it is impossible to finish the page as long as the DVDs section of the library itself remains unfinished. still, there's no point in deleting that page as long as it'll be readded in some months--i'll ask mr. roberts whether or not there's anything we can put on that page before the library finally kicks its selection of DVDs into action.

**Comment by kid47** [comment]
For the time being, I'd say just leave DVDs out, and then add it in later once we come to a solution

**Comment by owmygreenmatter** [comment]
i agree, it looks like that's what'll happen. still, just to err on the side of caution, i'm going to wait a little while for a response from mr. roberts (as he is basically our client here).
also, i've put the library pathways pdfs in wrappers and pushed it to my master branch. please forgive my inexperience, but will i have to make a new pull request or can i add that commit to this request? i'm assuming the former.

**Comment by owmygreenmatter** [comment]
alright, mr. roberts has kindly provided me the pdf file, so the DVDs page is finally finished. i've also pushed this change to my master branch.

**Comment by kid47** [comment]
I'll reopen it once I have access again. Apparently you can't over mobile

**Comment by owmygreenmatter** [comment]
is that the best course of action? i did make a second pull request but if it's unnecessary then i'll go close it

**Comment by kid47** [comment]
Oh, didn't notice that. Nevermind then

**Pull request closed without merging**
